### ISSUE TITLE
Notifications are cut off

### ISSUE THREAD

**Issue by TheSniperzzz** [CreatureSurvive/motuumLS-IssueTracker#32] opened 2018-01-21 17:51 UTC
iOS 10.2, iPhone 5s / motuumLS version: 3.0.8.6

Notifications are sometimes cut off (both on LS and NC) while using remove headers.

Glitched Notification: https://i.imgur.com/qeQkJBG.jpg
Normal Notification: https://i.imgur.com/3ZjHwmJ.jpg
Another example: https://i.imgur.com/T4uwdFl.jpg

**Comment by CreatureSurvive** [comment] 2018-01-22 01:03
@TheSniperzzz I was recently informed of this issue by one of my beta testers. I've found the cause of the issue and am working on a fix. The issue is related to removing the notification headers, as a temporary fix you can disable that feature. Hopefully I'll have a fix out very soon.

**Comment by TheSniperzzz** [comment] 2018-01-22 08:42
That's exactly what i did, don't worry and take your time!

If I can request a thing, it would be useful to have an option to keep the time of the notifications (10 min ago etc) even with removed headers but i don't know if it's a possible thing

**Comment by CreatureSurvive** [comment] 2018-01-24 06:31
@TheSniperzzz this issue is fixed in version 3.0.8.8

As the keeping the timestamp, that shouldn't be too hard, I'll just have to figure out how to style it so everything fits nicely in the notification cell.

**Closed as completed by CreatureSurvive** 2018-01-24 06:31 UTC
