### ISSUE TITLE
Tapping on "Edit" button crashes Settings

### ISSUE THREAD

**Issue by HenryB96** [CreatureSurvive/motuumLS-IssueTracker#11] opened 2017-05-31 04:38 UTC
If you edit the position of a label by manually typing in a value, an edit button will appear in the top right of the screen. Clicking on that edit button crashes the Settings app

**Comment by CreatureSurvive** [comment] 2017-05-31 04:48
I've never noticed this before, I'll look into it.

**Comment by CreatureSurvive** [comment] 2017-06-14 16:03
I finally found the cause of this issue and fixed it. in addition to fixing this I managed to fix the save button for input fields disappearing/not showing up. This will be included in the next update.

**Closed as completed** 2017-07-06 09:09 UTC
